### In each cell complete the task using pandas

In [4]:
import pandas as pd
import numpy as np

Read in the titanic.csv file in the `~/data` directory as a pandas dataframe called **df**

Or you can also use this link: https://raw.githubusercontent.com/daniel-dc-cd/data_science/master/module_3_Python/data/titanic.csv

In [5]:
df = pd.read_csv('https://raw.githubusercontent.com/daniel-dc-cd/data_science/master/module_3_Python/data/titanic.csv')

Display the head of the dataframe

In [6]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.6+ KB

In [8]:
df.shape

(891, 12)

In [9]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

What is the percentage of people who survived? (hint find the mean of the survival column)

In [10]:
print(round(df.Survived.mean()*100,4), "%")

38.3838 %

How many women and how many man survived?

In [11]:
survived_per_gender = df.groupby(['Sex','Survived']).Survived.count()
print(survived_per_gender)
survived_per_gender.unstack()

Sex     Survived
female  0            81
        1           233
male    0           468
        1           109
Name: Survived, dtype: int64

Survived    0    1
Sex
female     81  233
male      468  109

What is the percentage of people that survived who paid a fare less than 10?

In [12]:
df1 = df[(df.Fare <10)]
df1.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.250,NaN,S
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.925,NaN,S

In [13]:
survived_fare_less_10 = df1[df1.Survived == 1]
Survived = df[df.Survived == 1]
print("percentage of people that survived who paid a fare less than 10: ", 
     (len(survived_fare_less_10)/len(Survived))*100,"%")

percentage of people that survived who paid a fare less than 10:  19.5906432748538 %

What is the average age of those who didn't survive?

In [14]:
df[df.Survived == 0].Age.mean()

30.62617924528302

What is the average age of those who did survive?

In [15]:
df[df.Survived == 1].Age.mean()

28.343689655172415

What is the average age of those who did and didn't survive grouped by gender?

In [16]:
age_mean = df.groupby(['Sex','Survived']).Age.mean()
print(age_mean)
age_mean.unstack()

Sex     Survived
female  0           25.046875
        1           28.847716
male    0           31.618056
        1           27.276022
Name: Age, dtype: float64

Survived          0          1
Sex
female    25.046875  28.847716
male      31.618056  27.276022

## Tidy GDP

Manipulate the GDP.csv file and make it tidy, the result should be a pandas dataframe with the following columns:
* Country Name
* Country Code
* Year
* GDP

https://raw.githubusercontent.com/daniel-dc-cd/data_science/master/module_3_Python/data/GDP.csv

In [18]:
df = pd.read_csv('https://raw.githubusercontent.com/daniel-dc-cd/data_science/master/module_3_Python/data/GDP.csv', skiprows=4)
df.head(2)

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,Unnamed: 62
0,Aruba,ABW,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.498933e+09,2.467704e+09,2.584464e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,AFG,GDP (current US$),NY.GDP.MKTP.CD,5.377778e+08,5.488889e+08,5.466667e+08,7.511112e+08,8.000000e+08,1.006667e+09,...,1.248694e+10,1.593680e+10,1.793024e+10,2.053654e+10,2.026425e+10,2.061610e+10,1.921556e+10,1.946902e+10,2.081530e+10,NaN

In [22]:
df.shape

(264, 63)

In [23]:
df.drop(['Indicator Name' , 'Indicator Code'], axis=1)

,Country Name,Country Code,1960,1961,1962,1963,1964,1965,1966,1967,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,Unnamed: 62
0,Aruba,ABW,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.498933e+09,2.467704e+09,2.584464e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,AFG,5.377778e+08,5.488889e+08,5.466667e+08,7.511112e+08,8.000000e+08,1.006667e+09,1.400000e+09,1.673333e+09,...,1.248694e+10,1.593680e+10,1.793024e+10,2.053654e+10,2.026425e+10,2.061610e+10,1.921556e+10,1.946902e+10,2.081530e+10,NaN
2,Angola,AGO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.549239e+10,8.252614e+10,1.041158e+11,1.139232e+11,1.249125e+11,1.267302e+11,1.026212e+11,9.533720e+10,1.242094e+11,NaN
3,Albania,ALB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.204421e+10,1.192695e+10,1.289087e+10,1.231978e+10,1.277628e+10,1.322824e+10,1.138693e+10,1.188368e+10,1.303935e+10,NaN
4,Andorra,AND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.660531e+09,3.355695e+09,3.442063e+09,3.164615e+09,3.281585e+09,3.350736e+09,2.811489e+09,2.877312e+09,3.012914e+09,NaN
5,Arab World,ARB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.795820e+12,2.109551e+12,2.501305e+12,2.786139e+12,2.866038e+12,2.906918e+12,2.554480e+12,2.500164e+12,2.591047e+12,NaN
6,United Arab Emirates,ARE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.535474e+11,2.897873e+11,3.506660e+11,3.745906e+11,3.901076e+11,4.031371e+11,3.581351e+11,3.570451e+11,3.825751e+11,NaN
7,Argentina,ARG,NaN,NaN,2.445060e+10,1.827212e+10,2.560525e+10,2.834471e+10,2.863047e+10,2.425667e+10,...,3.329765e+11,4.236274e+11,5.301633e+11,5.459824e+11,5.520251e+11,5.263197e+11,5.947493e+11,5.548609e+11,6.375904e+11,NaN
8,Armenia,ARM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.647937e+09,9.260285e+09,1.014211e+10,1.061932e+10,1.112147e+10,1.160951e+10,1.055334e+10,1.054614e+10,1.153659e+10,NaN
9,American Samoa,ASM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.780000e+08,5.760000e+08,5.740000e+08,6.440000e+08,6.410000e+08,6.430000e+08,6.590000e+08,6.580000e+08,NaN,NaN
10,Antigua and Barbuda,ATG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.224253e+09,1.152469e+09,1.142043e+09,1.211412e+09,1.192925e+09,1.280133e+09,1.364863e+09,1.460145e+09,1.532398e+09,NaN
11,Australia,AUS,1.857319e+10,1.964834e+10,1.988801e+10,2.150185e+10,2.375854e+10,2.593124e+10,2.726173e+10,3.038974e+10,...,9.264482e+11,1.144261e+12,1.394281e+12,1.543411e+12,1.573697e+12,1.464955e+12,1.349034e+12,1.208039e+12,1.323421e+12,NaN
12,Austria,AUT,6.592694e+09,7.311750e+09,7.756110e+09,8.374175e+09,9.169984e+09,9.994071e+09,1.088768e+10,1.157943e+10,...,4.001723e+11,3.918927e+11,4.311203e+11,4.094252e+11,4.300687e+11,4.418854e+11,3.820659e+11,3.908000e+11,4.165957e+11,NaN
13,Azerbaijan,AZE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.429149e+10,5.290270e+10,6.595163e+10,6.968394e+10,7.416444e+10,7.524429e+10,5.307437e+10,3.786752e+10,4.074779e+10,NaN
14,Burundi,BDI,1.960000e+08,2.030000e+08,2.135000e+08,2.327500e+08,2.607500e+08,1.589950e+08,1.654446e+08,1.782971e+08,...,1.739781e+09,2.026864e+09,2.355652e+09,2.472385e+09,2.714506e+09,3.093647e+09,3.066681e+09,3.007029e+09,3.477502e+09,NaN
15,Belgium,BEL,1.165872e+10,1.240015e+10,1.326402e+10,1.426002e+10,1.596011e+10,1.737146e+10,1.865188e+10,1.999204e+10,...,4.845528e+11,4.835480e+11,5.270085e+11,4.978842e+11,5.209255e+11,5.307710e+11,4.550396e+11,4.675455e+11,4.926813e+11,NaN
16,Benin,BEN,2.261956e+08,2.356682e+08,2.364349e+08,2.539276e+08,2.698190e+08,2.899087e+08,3.029253e+08,3.062220e+08,...,7.097199e+09,6.970241e+09,7.814081e+09,8.152554e+09,9.157356e+09,9.707432e+09,8.291156e+09,8.573160e+09,9.273558e+09,NaN
17,Burkina Faso,BFA,3.304428e+08,3.502472e+08,3.795672e+08,3.940407e+08,4.103218e+08,4.229168e+08,4.338898e+08,4.507540e+08,...,8.369175e+09,8.979967e+09,1.072406e+10,1.116606e+10,1.194718e+10,1.237739e+10,1.041930e+10,1.144878e+10,1.287311e+10,NaN
18,Bangladesh,BGD,4.274894e+09,4.817580e+09,5.081413e+09,5.319458e+09,5.386055e+09,5.906637e+09,6.439688e+09,7.253575e+09,...,1.024778e+11,1.152791e+11,1.286379e+11,1.333557e+11,1.499905e+11,1.728855e+11,1.950787e+11,2.214152e+11,2.497239e+11,NaN
19,Bulgaria,BGR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.188448e+10,5.061006e+10,5.741841e+10,5.390302e+10,5.575875e+10,5.673199e+10,5.019910e+10,5.324089e+10,5.683152e+10,NaN
20,Bahrain,BHR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.293822e+10,2.571327e+10,2.877660e+10,3.074931e+10,3.253955e+10,3.338771e+10,3.112585e+10,3.215269e+10,3.530713e+10,NaN
21,"Bahamas, The",BHS,1.698039e+08,1.900980e+08,2.122549e+08,2.377451e+08,2.666667e+08,3.003922e+08,3.400000e+08,3.901961e+08,...,9.981960e+09,1.009576e+10,1.007045e+10,1.072050e+10,1.062760e+10,1.095730e+10,1.179230e+10,1.183880e+10,1.216210e+10,NaN
22,Bosnia and Herzegovina,BIH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.761384e+10,1.717678e+10,1.864472e+10,1.722685e+10,1.817850e+10,1.855834e+10,1.620970e+10,1.691109e+10,1.816858e+10,NaN
23,Belarus,BLR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.920952e+10,5.722249e+10,6.175779e+10,6.568510e+10,7.552798e+10,7.881384e+10,5.645473e+10,4.772266e+10,5.444237e+10,NaN
24,Belize,BLZ,2.807189e+07,2.996437e+07,3.185692e+07,3.374941e+07,3.619383e+07,4.006993e+07,4.440559e+07,4.737931e+07,...,1.336957e+09,1.397113e+09,1.487006e+09,1.573670e+09,1.612574e+09,1.703951e+09,1.778568e+09,1.820159e+09,1.838000e+09,NaN
25,Bermuda,BMU,8.446665e+07,8.924999e+07,9.414999e+07,9.636665e+07,1.075667e+08,1.143390e+08,1.341734e+08,1.551030e+08,...,5.806378e+09,5.744414e+09,5.550771e+09,5.537537e+09,5.573710e+09,NaN,NaN,NaN,NaN,NaN
26,Bolivia,BOL,5.631101e+08,6.125189e+08,6.697225e+08,7.211430e+08,8.125431e+08,9.088745e+08,9.940446e+08,1.084060e+09,...,1.733999e+10,1.964963e+10,2.396303e+10,2.708450e+10,3.065934e+10,3.299619e+10,3.300020e+10,3.394113e+10,3.750864e+10,NaN
27,Brazil,BRA,1.516557e+10,1.523685e+10,1.992629e+10,2.302148e+10,2.121189e+10,2.179004e+10,2.706272e+10,3.059183e+10,...,1.667020e+12,2.208872e+12,2.616202e+12,2.465189e+12,2.472807e+12,2.455994e+12,1.802214e+12,1.793989e+12,2.055506e+12,NaN
28,Barbados,BRB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.434050e+09,4.461650e+09,4.660900e+09,4.656350e+09,4.612500e+09,4.608350e+09,4.584150e+09,4.529050e+09,4.796846e+09,NaN
29,Brunei Darussalam,BRN,NaN,NaN,NaN,NaN,NaN,1.140402e+08,1.327584e+08,1.390304e+08,...,1.073237e+10,1.370737e+10,1.852532e+10,1.904850e+10,1.809383e+10,1.709834e+10,1.293039e+10,1.140065e+10,1.212809e+10,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,Latin America & the Caribbean (IDA & IBRD coun...,TLA,7.632394e+10,8.099870e+10,9.331069e+10,9.365012e+10,1.040022e+11,1.116928e+11,1.225325e+11,1.251588e+11,...,4.118809e+12,5.146370e+12,5.870414e+12,5.925333e+12,6.070270e+12,6.187003e+12,5.278059e+12,5.134442e+12,5.704713e+12,NaN
235,Timor-Leste,TLS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.199550e+09,3.998697e+09,5.681941e+09,6.671048e+09,5.649813e+09,4.045378e+09,3.104426e+09,2.521008e+09,2.954621e+09,NaN
236,Middle East & North Africa (IDA & IBRD countries),TMN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.188669e+12,1.374621e+12,1.558059e+12,1.716997e+12,1.610655e+12,1.584604e+12,1.422430e+12,1.431082e+12,1.417010e+12,NaN
237,Tonga,TON,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.181666e+08,3.694852e+08,4.230118e+08,4.723583e+08,4.506864e+08,4.439111e+08,4.354382e+08,4.015620e+08,4.260575e+08,NaN
238,South Asia (IDA & IBRD),TSA,4.653588e+10,4.963926e+10,5.296996e+10,5.956412e+10,6.820724e+10,7.330213e+10,6.163811e+10,6.785967e+10,...,1.665591e+12,2.042144e+12,2.272004e+12,2.297911e+12,2.356854e+12,2.581994e+12,2.695273e+12,2.903124e+12,3.291738e+12,NaN
239,Sub-Saharan Africa (IDA & IBRD countries),TSS,2.992415e+10,3.108149e+10,3.368908e+10,3.862969e+10,3.768953e+10,4.199301e+10,4.533254e+10,4.480287e+10,...,1.023157e+12,1.364275e+12,1.538451e+12,1.613329e+12,1.702769e+12,1.783849e+12,1.610061e+12,1.512473e+12,1.648714e+12,NaN
240,Trinidad and Tobago,TTO,5.356701e+08,5.849612e+08,6.193192e+08,6.782354e+08,7.118934e+08,7.365689e+08,7.237356e+08,7.619815e+08,...,1.917520e+10,2.215795e+10,2.543301e+10,2.562292e+10,2.657852e+10,2.719986e+10,2.440250e+10,2.232001e+10,2.210478e+10,NaN
241,Tunisia,TUN,NaN,NaN,NaN,NaN,NaN,9.910476e+08,1.040952e+09,1.085714e+09,...,4.345494e+10,4.405093e+10,4.581063e+10,4.504411e+10,4.625106e+10,4.758791e+10,4.315671e+10,4.206255e+10,4.025668e+10,NaN
242,Turkey,TUR,1.399507e+10,8.022222e+09,8.922222e+09,1.035556e+10,1.117778e+10,1.194444e+10,1.412222e+10,1.566667e+10,...,6.446399e+11,7.719018e+11,8.325237e+11,8.739822e+11,9.505794e+11,9.341859e+11,8.597969e+11,8.637216e+11,8.511024e+11,NaN
243,Tuvalu,TUV,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.710108e+07,3.182352e+07,3.871183e+07,3.767173e+07,3.750912e+07,3.729059e+07,3.555604e+07,3.657261e+07,3.973132e+07,NaN
244,Tanzania,TZA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.857378e+10,3.140791e+10,3.387863e+10,3.908775e+10,4.441362e+10,4.821973e+10,4.562349e+10,4.738840e+10,5.209032e+10,NaN
245,Uganda,UGA,4.230084e+08,4.415241e+08,4.490126e+08,5.161478e+08,5.890566e+08,8.848739e+08,9.257703e+08,9.676471e+08,...,1.816890e+10,2.018650e+10,2.017603e+10,2.311429e+10,2.459955e+10,2.729188e+10,2.710265e+10,2.407893e+10,2.589106e+10,NaN
246,Ukraine,UKR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.172278e+11,1.360132e+11,1.631597e+11,1.757814e+11,1.833101e+11,1.335034e+11,9.103096e+10,9.327048e+10,1.121542e+11,NaN
247,Upper middle income,UMC,1.864658e+11,1.701712e+11,1.789028e+11,1.968965e+11,2.155423e+11,2.407044e+11,2.676685e+11,2.776638e+11,...,1.268526e+13,1.536243e+13,1.836527e+13,1.970327e+13,2.098177e+13,2.170348e+13,2.021076e+13,2.010892e+13,2.216842e+13,NaN
248,Uruguay,URY,1.242289e+09,1.547389e+09,1.710004e+09,1.539681e+09,1.975702e+09,1.890769e+09,1.809184e+09,1.597721e+09,...,3.166091e+10,4.028448e+10,4.796244e+10,5.126439e+10,5.753123e+10,5.723601e+10,5.327430e+10,5.268761e+10,5.615697e+10,NaN
249,United States,USA,5.433000e+11,5.633000e+11,6.051000e+11,6.386000e+11,6.858000e+11,7.437000e+11,8.150000e+11,8.617000e+11,...,1.441874e+13,1.496437e+13,1.551793e+13,1.615526e+13,1.669152e+13,1.742761e+13,1.812071e+13,1.862448e+13,1.939060e+13,NaN
250,Uzbekistan,UZB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.368922e+10,3.933277e+10,4.591519e+10,5.182157e+10,5.769045e+10,6.306708e+10,6.690380e+10,6.706757e+10,4.871769e+10,NaN
251,St. Vincent and the Grenadines,VCT,1.306656e+07,1.399988e+07,1.452488e+07,1.370822e+07,1.475821e+07,1.510821e+07,1.609987e+07,1.583518e+07,...,6.749225e+08,6.812260e+08,6.761294e+08,6.929337e+08,7.212071e+08,7.251852e+08,7.566667e+08,7.655556e+08,7.896296e+08,NaN
252,"Venezuela, RB",VEN,8.736939e+09,9.058121e+09,1.002200e+10,1.082388e+10,9.111000e+09,9.496244e+09,9.984400e+09,1.035642e+10,...,3.297876e+11,3.931924e+11,3.164822e+11,3.812862e+11,3.710054e+11,4.823593e+11,NaN,NaN,NaN,NaN
253,British Virgin Islands,VGB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
254,Virgin Islands (U.S.),VIR,2.420000e+07,2.570000e+07,3.690000e+07,4.140000e+07,5.380000e+07,6.650000e+07,8.410000e+07,1.154000e+08,...,4.203000e+09,4.339000e+09,4.239000e+09,4.095000e+09,3.764000e+09,3.624000e+09,3.765000e+09,NaN,NaN,NaN
255,Vietnam,VNM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.060147e+11,1.159317e+11,1.355394e+11,1.558200e+11,1.712220e+11,1.862047e+11,1.932411e+11,2.052762e+11,2.238640e+11,NaN
256,Vanuatu,VUT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.100666e+08,7.008043e+08,7.921497e+08,7.817029e+08,8.017876e+08,8.149543e+08,7.379172e+08,7.879426e+08,8.628798e+08,NaN
257,World,WLD,1.365887e+12,1.420995e+12,1.526067e+12,1.642848e+12,1.799787e+12,1.960681e+12,2.127233e+12,2.263327e+12,...,6.013844e+13,6.595667e+13,7.329734e+13,7.496562e+13,7.705059e+13,7.913144e+13,7.484273e+13,7.593681e+13,8.068379e+13,NaN
258,Samoa,WSM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.609595e+08,6.430467e+08,7.397851e+08,8.011686e+08,8.048085e+08,8.035895e+08,8.039858e+08,7.863563e+08,8.566265e+08,NaN
259,Kosovo,XKX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.653793e+09,5.829934e+09,6.686683e+09,6.500193e+09,7.073420e+09,7.386891e+09,6.439947e+09,6.715487e+09,7.128691e+09,NaN
260,"Yemen, Rep.",YEM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.513027e+10,3.090675e+10,3.272642e+10,3.540133e+10,4.041524e+10,4.322858e+10,3.460248e+10,1.821333e+10,NaN,NaN
261,South Africa,ZAF,7.575248e+09,7.972841e+09,8.497830e+09,9.423212e+09,1.037379e+10,1.133417e+10,1.235475e+10,1.377712e+10,...,2.972167e+11,3.752981e+11,4.168782e+11,3.963327e+11,3.668294e+11,3.509046e+11,3.177410e+11,2.957627e+11,3.494193e+11,NaN
262,Zambia,ZMB,7.130000e+08,6.962857e+08,6.931429e+08,7.187143e+08,8.394286e+08,1.082857e+09,1.264286e+09,1.368000e+09,...,1.532834e+10,2.026556e+10,2.346010e+10,2.550337e+10,2.804546e+10,2.715063e+10,2.115439e+10,2.095475e+10,2.580867e+10,NaN
263,Zimbabwe,ZWE,1.052990e+09,1.096647e+09,1.117602e+09,1.159512e+09,1.217138e+09,1.311436e+09,1.281750e+09,1.397002e+09,...,8.621574e+09,1.014186e+10,1.209845e+10,1.424249e+10,1.545177e+10,1.589105e+10,1.630467e+10,1.661996e+10,1.784582e+10,NaN

In [29]:
formatted_df = pd.melt(df,
                       ["Country Name","Country Code"],
                       var_name="Year",
                       value_name="GDP")
formatted_df = formatted_df.sort_values(by=["Country Name","Year"]).set_index("Country Name")
formatted_df.head(10)

             Country Code  Year          GDP
Country Name
Afghanistan           AFG  1960  5.37778e+08
Afghanistan           AFG  1961  5.48889e+08
Afghanistan           AFG  1962  5.46667e+08
Afghanistan           AFG  1963  7.51111e+08
Afghanistan           AFG  1964        8e+08
Afghanistan           AFG  1965  1.00667e+09
Afghanistan           AFG  1966      1.4e+09
Afghanistan           AFG  1967  1.67333e+09
Afghanistan           AFG  1968  1.37333e+09
Afghanistan           AFG  1969  1.40889e+09